CREATE TABLE inquiries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
    email VARCHAR(255) NOT NULL
    subject VARCHAR(200) NOT NULL
    message TEXT NOT NULL
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
